In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,3,5,6]] , np.int64)

In [3]:
myarr

array([[1, 3, 5, 6]])

In [4]:
myarr[0,1]

3

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 1, 45,  5,  6]])

In [8]:
list = np.array([[1,2,3],[2,3,7],[6,4,3]])

In [9]:
list

array([[1, 2, 3],
       [2, 3, 7],
       [6, 4, 3]])

In [10]:
list[0,2]

3

In [11]:
list.dtype

dtype('int64')

In [12]:
list.shape

(3, 3)

In [13]:
list.size

9

In [14]:
zero = np.zeros((2,5))

In [15]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,4,4)

In [20]:
lspace
#equally spaced integer in range 1 to 4 both included

array([1., 2., 3., 4.])

In [27]:
emp = np.empty((1,15))

In [29]:
emp
#random element filled array

array([[ 0.    ,  0.    ,  1.    ,  0.0625,  0.25  ,  1.    ,  1.    ,
         1.    ,  1.    ,  5.0625,  2.25  ,  1.    , 16.    ,  4.    ,
         1.    ]])

In [32]:
ide = np.identity(5)

In [33]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
ide.shape

(5, 5)

In [36]:
i = np.arange(99)

In [37]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
i = i.reshape(3,33)

In [39]:
i

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
i = i.ravel()

In [42]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [45]:
ar = np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
ar.shape

(3, 3)

In [51]:
ar.sum(axis=0)

array([12, 15, 18])

In [53]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [54]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
ar.flat

In [61]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [63]:
ar.ndim

2

In [64]:
ar.size

9

In [66]:
ar.nbytes

72

In [74]:
ar.argmin()

0

In [69]:
ar.argmax()
#it flat the array and fing the index with the max value

8

In [72]:
ar.argsort()
#it tells the sorted syntax

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [73]:
ar.T.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [78]:
list+ar 
#matrix addition

array([[ 2,  4,  6],
       [ 6,  8, 13],
       [13, 12, 12]])